version: '3.8'

services:
  database:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: adhaar-validation
      POSTGRES_USER: "your_username"
      POSTGRES_PASSWORD: "your_password"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend # Path to your backend folder
      dockerfile: Dockerfile.backend
    restart: always
    environment:
      DATABASE_URL: "Postgre-uri"
    volumes:
      - ./backend_folder:/app
    ports:
      - "8000:8000"
    depends_on:
      - database

  frontend:
    build:
      context: ./udyam-form # Path to your frontend folder
      dockerfile: Dockerfile.frontend
    restart: always
    environment:
      NEXT_PUBLIC_BACKEND_URL: "http://localhost:8000"
    volumes:
      - ./frontend_folder:/app
      - /app/node_modules # Prevents host node_modules from overriding container's
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: